all:
	./build.sh

install:
	cp wgo/*.min.js wgo/*.css /home/cgosboar/public_html/wgo/
	mkdir -p /home/cgosboar/public_html/js
	mkdir -p /home/cgosboar/public_html/css
	cp list/*.js /home/cgosboar/public_html/js
	cp list/*.css /home/cgosboar/public_html/css
	cp list/list.html viewer.html /home/cgosboar/public_html/19x19/
