all:
	./build.sh

install:
	cp wgo/*.min.js wgo/*.css /home/cgosboar/public_html/wgo/
	mkdir -p /home/cgosboar/public_html/js
	mkdir -p /home/cgosboar/public_html/css
	cp cgos_viewer/*.js /home/cgosboar/public_html/js
	cp cgos_viewer/*.css /home/cgosboar/public_html/css
	cp cgos_viewer/*.html /home/cgosboar/public_html/9x9/
	cp cgos_viewer/*.html /home/cgosboar/public_html/19x19/
